### ISSUE TITLE
Lost websocket connection

### ISSUE THREAD

**Issue by youzhi1233** [matthuisman/docker-kodi-headless#14]
Lost websocket connection

**Comment by matthuisman** [comment]
Most likely Kodi is crashing for various reasons. You'll need to check the log

**Comment by acatinon** [comment]
Hello,

I'm having the same problem, so there is a bit of context:

I changed the published port for web sockets:
```
-p 8098:9090
```
So I guess the browser is trying to connect to the port 9090 instead of the 8098 published port.

I didn't found anything to change the web sockets port in `advancedsettings.xml`

@matthuisman do you think something can be done?

Thanks

**Comment by matthuisman** [comment]
```
<jsonrpc>
    <tcpport>8098</tcpport>
</jsonrpc>
```

**Comment by matthuisman** [comment]
Sounds like Kodi is dying. View the Kodi log to get more information
